### ISSUE TITLE
Problem with starting the bot.

### ISSUE THREAD

**Issue by baid55** [ahoys/tunnelerjs#4]
Hello, I have followed the guide, and when I get to the final step I type 'node tunneler' into my console and I get the following errors.

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Help would be appreciated, this seems like the only decent bot for antispam.
Thanks.

**Comment by ahoys** [comment]
Hi, did you download a stable release, instead of a work-in-progress one? The releases can be found here: [releases download](https://github.com/ahoys/tunnelerjs/releases).

Questions:
1. What OS are you using?
2. Which command prompt?
3. What is your Node.js' version? You can find this out by typing "node -v" to a command prompt.

Also:
- Make sure the installation directory contains "node_modules" sub-folder. If not, run **npm install** again.
